# This file is a template, and might need editing before it works on your project.
stages:
  - test
  - deploy

before_script:
  - python -V # Print out python version for debugging
  - python -m venv venv
  - source venv/bin/activate
  - pip install pybuilder
  - pyb install_dependencies

test:
  stage: test
  script:
  - pyb run_unit_tests -v

coverage:
  stage: test
  script:
  - pyb analyze
  coverage: '/Overall coverage is .*?(\d{1,3}\%)$/'

publish:
  stage: deploy
  script:
  - pyb publish

pages:
  stage: deploy
  script:
  - pyb analyze
  - pyb sphinx_generate_documentation
  - mv target/doc public/
  - mkdir public/coverage_html
  - mv target/reports/coverage_html public/coverage_html

  artifacts:
    paths:
    - public
  only:
  - master
